In [1]:
import numpy

In [6]:
# Define the inputs, weights, and biases
inputs = np.array([
    [1.0, 2.0, -1.5],
    [0.2, 0.5, 2.0],
    [5.0, 2.7, 0.8],
    [3.0, 2.5, -1.0]
])

# Adjust the weights to match input shape (4, 3) rather than (4, 4)
weights = np.array([
    [2.0, -0.8, 3.3],
    [-0.5, 1.0, -0.26],
    [2.0, 3.0, -0.91],
    [0.26, -0.5, -0.27]
])

# Adjust biases to match output shape
biases = np.array([0.2, 2.0, -0.5, 0.5])

# Compute the dot product of inputs and the transpose of weights
outputs = np.dot(inputs, weights.T) - biases

print("Outputs:\n", outputs)


Outputs:
 [[-4.75  -0.11   9.865 -0.835]]


In [10]:
inputs = [[1.0, 2.0, 3.0, 2.5],
 [2.0, 5.0, -1.0, 2.0],
 [-1.5, 2.7, 3.3, -0.8]]


weights = [[0.2, 0.8, -0.5, 1.0],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]


biases = [2.0, 3.0, 0.5]


layer_outputs = np.dot(inputs, np.array(weights).T) + biases


print(layer_outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [13]:
inputs = [[1, 2, 3, 2.5],
 [2., 5., -1., 2],
 [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

weights2  = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]

layer_outputs1 = np.dot(inputs, np.array(weights).T) + biases

layer_outputs1

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [20]:
weights2  = [[0.2, 0.8, -0.5]]


layer_outputs2=  np.dot(layer_outputs1, np.array(weights2).T) + biases[0]


print(layer_outputs, "\n\n", layer_outputs2)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]] 

 [[2.7355]
 [2.232 ]
 [3.1098]]


In [23]:
inputs = [[1, 2, 3, 2.5],
 [2., 5., -1., 2],
 [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]
weights2 = [[0.1, -0.14, 0.5],
 [-0.5, 0.12, -0.33]]
biases2 = [-1, 2, -0.5]
layer1_outputs = np.dot(inputs, np.array(weights).T) + biases
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2[0:2]


layer2_outputs

array([[ 0.5031 , -1.04185],
       [ 0.2434 , -2.7332 ],
       [-0.99314,  1.41254]])